### ISSUE TITLE
Calling a C# method from JS

### ISSUE THREAD

**Issue by gaetandezeiraud** [SupinePandora43/UltralightNet#78]
I saw this old issue https://github.com/SupinePandora43/UltralightNet/issues/24 but doesn't help me a lot.
How to call a C# method from JS? Like in the Ultralight documentation for C (https://docs.ultralig.ht/docs/calling-a-c-function-from-js). It is just not possible yet?

Thanks!

**Comment by SupinePandora43** [comment]
JS bindings were added in #75, but this wasn't published to nuget. You'll have to use UltralightNet from the [`develop`](https://github.com/SupinePandora43/UltralightNet/tree/develop) branch.

**Comment by gaetandezeiraud** [comment]
Yes that's what I did. THANKS !
