### ISSUE TITLE
Cannot load local file

### ISSUE THREAD

**Issue by meznoos** [SupinePandora43/UltralightNet#80]
Hi, I tried to load local html, but nothing loaded, no log too.

 AppCoreMethods.SetPlatformFontLoader();
  AppCoreMethods.ulEnableDefaultLogger("./ullog.txt");
  ULPlatform.FileSystem = ULPlatform.DefaultFileSystem;
  ULPlatform.Logger = ULPlatform.DefaultLogger;

        var cfg = new ULConfig
        {
            ForceRepaint = false,
            CachePath = "/cache",
        };
        var setting = new ULSettings
        {
            ForceCPURenderer = false,
        };
        _app = ULApp.Create(setting,cfg);
        _scale = ScreenHelper.GetScaleFactor(Screen);
 
        var viewConfig = new ULViewConfig()
        {
            // IsAccelerated = false,
            IsTransparent = false,
            InitialDeviceScale = _scale,
            
        };
        
        _view = _app.Renderer.CreateView(1920, 1080, viewConfig, _app.Renderer.CreateSession(true, "thecookies"));

        _view.URL ="file:///index.html";
        // _view.URL = "https://docs.ultralig.ht/docs/logging-console-messages";

**Comment by SupinePandora43** [comment]
Sorry for the misconception, but the "`DefaultFileSystem`" is actually "_Default_**_ResourceOnly_**_FileSystem_". Term _resources_ in this case refers to the two most important files that are required for Ultralight's comfortable usage: cacert.pem for loading https pages, and icu.something.dt for not straight-up crashing and iirc _localization_/UTF/Unicode support.

**Comment by SupinePandora43** [comment]
Use `AppCoreMethods.ulEnablePlatformFileSystem`
